/* Crear la base de datos */
CREATE DATABASE dbStocks;

/* Crear las tablas */
CREATE TABLE dbStocks.PRODUCTOS (
	COD_PROD INT(5) NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(25) NOT NULL,
	CATEGORIA VARCHAR(25) NOT NULL,
	DESCRIPCION VARCHAR(100),
	PRECIO_COMPRA INT(6) NOT NULL,
    PRECIO_VENTA INT(6) NOT NULL,
	PRIMARY KEY (COD_PROD)
);

CREATE TABLE dbStocks.SOCIOS (
	COD_TIENDA INT(5) NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(25) NOT NULL,
	DIRECCION VARCHAR(35) NOT NULL,
	CIUDAD VARCHAR(20) NOT NULL,
	EMAIL VARCHAR(20) NOT NULL,
    TELEFONO VARCHAR(9) NOT NULL,
    RESPONSABLE VARCHAR(20) NOT NULL,
	PRIMARY KEY (COD_TIENDA)
);

CREATE TABLE dbStocks.STOCKS (	
	COD_TIENDA INT(5) NOT NULL,
	COD_PROD INT(5) NOT NULL,
    STOCK INT(6) NOT NULL ,
    FOREIGN KEY(COD_TIENDA) REFERENCES SOCIOS(COD_TIENDA),
    FOREIGN KEY(COD_PROD) REFERENCES PRODUCTOS(COD_PROD)
);

/* Insertar valores de prueba */
INSERT INTO dbStocks.PRODUCTOS (NOMBRE, CATEGORIA, DESCRIPCION, PRECIO_COMPRA, PRECIO_VENTA) 
VALUES ('Peladillo', 'Fruta', 'De piel lustrosa y carne dura y pegada al hueso', 3, 6);
INSERT INTO dbStocks.PRODUCTOS (NOMBRE, CATEGORIA, DESCRIPCION, PRECIO_COMPRA, PRECIO_VENTA) 
VALUES ('Costilla cerdo', 'Carnicería', 'En tiras de 10cm de ancho', 7, 10);
INSERT INTO dbStocks.PRODUCTOS (NOMBRE, CATEGORIA, DESCRIPCION, PRECIO_COMPRA, PRECIO_VENTA) 
VALUES ('Pechuga pollo', 'Carnicería', 'Pollo campero', 3, 5);
INSERT INTO dbStocks.PRODUCTOS (NOMBRE, CATEGORIA, DESCRIPCION, PRECIO_COMPRA, PRECIO_VENTA) 
VALUES ('Fresa', 'Fruta', 'Fresón del sur', 2, 5);
INSERT INTO dbStocks.PRODUCTOS (NOMBRE, CATEGORIA, DESCRIPCION, PRECIO_COMPRA, PRECIO_VENTA) 
VALUES ('Trigo entero', 'Cereales', 'Trigo harinero', 1, 3);
INSERT INTO dbStocks.PRODUCTOS (NOMBRE, CATEGORIA, DESCRIPCION, PRECIO_COMPRA, PRECIO_VENTA) 
VALUES ('Manzana', 'Fruta', 'Primera calidad', 2, 5);

INSERT INTO dbStocks.SOCIOS (NOMBRE, DIRECCION, CIUDAD, EMAIL, TELEFONO, RESPONSABLE) 
VALUES ('Pastelería delicia', 'Calle dulces 20', 'A Coruña', 'pdelicia@panes.com', '981756887', 'FD239');
INSERT INTO dbStocks.SOCIOS (NOMBRE, DIRECCION, CIUDAD, EMAIL, TELEFONO, RESPONSABLE) 
VALUES ('Frutas Fructuoso', 'Calle peras 11', 'Santiago Compostela', 'ffuctuoso@gmail.com', '985665212', 'FD221');
INSERT INTO dbStocks.SOCIOS (NOMBRE, DIRECCION, CIUDAD, EMAIL, TELEFONO, RESPONSABLE) 
VALUES ('Carnicería Manolo', 'Calle viandas 36', 'A Coruña', 'carnmanolo@gmail.com', '985665687', 'FD123');

INSERT INTO dbStocks.STOCKS (COD_TIENDA, COD_PROD, STOCK) 
VALUES (1,1,60);
INSERT INTO dbStocks.STOCKS (COD_TIENDA, COD_PROD, STOCK) 
VALUES (1,4,42);
INSERT INTO dbStocks.STOCKS (COD_TIENDA, COD_PROD, STOCK) 
VALUES (1,5,1000);
INSERT INTO dbStocks.STOCKS (COD_TIENDA, COD_PROD, STOCK) 
VALUES (1,6,66);
INSERT INTO dbStocks.STOCKS (COD_TIENDA, COD_PROD, STOCK) 
VALUES (2,1,600);
INSERT INTO dbStocks.STOCKS (COD_TIENDA, COD_PROD, STOCK) 
VALUES (2,3,600);
INSERT INTO dbStocks.STOCKS (COD_TIENDA, COD_PROD, STOCK) 
VALUES (2,5,600);
INSERT INTO dbStocks.STOCKS (COD_TIENDA, COD_PROD, STOCK) 
VALUES (3,2,200);
INSERT INTO dbStocks.STOCKS (COD_TIENDA, COD_PROD, STOCK) 
VALUES (3,3,200);

/* Crear índices para mejorar performance */
CREATE INDEX idx_categoria ON dbStocks.PRODUCTOS (CATEGORIA);
CREATE INDEX idx_precio_venta ON dbStocks.PRODUCTOS (PRECIO_VENTA);

/* Consultas EXPLAIN
EXPLAIN SELECT * FROM dbStocks.PRODUCTOS WHERE dbStocks.PRODUCTOS.CATEGORIA = 'Fruta';
EXPLAIN SELECT * FROM dbStocks.PRODUCTOS WHERE dbStocks.PRODUCTOS.PRECIO_VENTA <= 5;
EXPLAIN SELECT COD_PROD, SUM(STOCK) 'CANTIDAD TOTAL' FROM dbStocks.STOCKS GROUP BY COD_PROD;
EXPLAIN SELECT COD_TIENDA, STOCK FROM dbStocks.STOCKS WHERE COD_PROD=1;
*/